version: 2
jobs:
  test:
    docker:
      - image: ${STAGING_ECR_URL}/kong-plugin-dev:testing
        aws_auth: &ecr_credentials
          aws_access_key_id: $STAGING_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $STAGING_AWS_SECRET_ACCESS_KEY
      - image: postgres
        environment:
          POSTGRES_DB: kong
          POSTGRES_USER: kong
          POSTGRES_PASSWORD: kong
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 60`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Test
          command: |
            wget -O /tmp/geolite.tar.gz http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
            mkdir /tmp/geolite/ && tar zxvf /tmp/geolite.tar.gz -C /tmp/geolite/

            export LUA_PATH="/root/project/?.lua;/root/project/?/init.lua;/kong/?.lua;;"
            cp spec/kong_tests.conf /kong/spec/
            cd /kong/
            # hack as kong busted doesn't return correct error code
            ./bin/busted /root/project/ | tee /dev/tty | grep '0 failures' && exit 0 || exit 1

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: org-global
